### ISSUE TITLE
Hi Masatoshi 

### ISSUE THREAD

**Issue by paulransfield** [mnishiguchi/react_concentration#3]
I am a beginner with React.js.

I appreciate you may be too busy to reply.

Thanks in advance.

I am keen on reusing your code base but get the following error at npm startup:

npm ERR! Linux 3.13.0-110-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.8.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! react_concentration@1.0.0 start: `node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react_concentration@1.0.0 start script 'node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js'.
npm ERR! This is most likely a problem with the react_concentration package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js

**Comment by mnishiguchi** [comment]
Hi Paul. Thank you for sending an issue. To be honest with you, I don't know exactly why it stopped working. It may be because of unlocked versions. I should have locked all the dependencies in the `package.json` file so that I could have been aware of what combination of dependencies worked. Because I did not do it, every time we clone this app and install npm dependencies, npm will install latest versions.

If you are a beginner, I will recommend using [`create-react-app`](https://github.com/facebookincubator/create-react-app), which provides you a playground where you can practice React without any configuration. I use it all the time because I am not a configuration expert.

When I have time, I will try to rewrite this app so that it works again! In the meantime, you can think how you would implement this type game your self. I don't think my solution is best because I was a react beginner when I created this. It will be a great exercise for you to understand how react works.

**Comment by paulransfield** [comment]
Hi again Masatoshi.  Thank you very much for taking the time to reply.  I'll certainly take a look at create-react-app.  And, if I get a work around for using webpack-dev-server, I'll let you know.  I tracked down one of the issues with running npm start with the current configuration, to be due to the version of webpack-dev-server, and a change in internal code structure for one line - causing an error.

I'll close this issue, and I look forward to getting your code-base redeployed.

Thanks again.

**Comment by mnishiguchi** [comment]
I am sure that you will get used to react programming soon because you seem passionate about coding. Please show me when you create something cool too!

**Comment by mnishiguchi** [comment]
Here is my remake app https://github.com/mnishiguchi/react-concentration-2
